zuul:
  routes:
    catalog-query:
      path: /catalogitems
      serviceId: catalog-query
    user-query:
      path: /read-users
      serviceId: user-query
    user-command:
      path: /users
      serviceId: user-command



